### ISSUE TITLE
不支持decimal返回值，报错。可能是json转换出错

### ISSUE THREAD

**Issue by nlh774** [Coldairarrow/DotNettyRPC#1]
public interface IOrderService
    {
        double CalculateFinalOrderSum(long userId, double originalSum);
    }

**Comment by Coldairarrow** [comment]
多谢反馈，我这边测试下

**Comment by Coldairarrow** [comment]
我测试了下，你这个接口没问题啊
返回类型改为decimal也没问题
![image](https://user-images.githubusercontent.com/25943840/50592774-817dc300-0ed0-11e9-9d67-c16f6fc166e8.png)

**Comment by nlh774** [comment]
我这边还是有错误，如下

![Uploading 1.png…]()

public interface IOrderService
    {
        decimal CalculateFinalOrderSum(long userId, decimal originalSum);
    }

public class OrderService : IOrderService
    {
        public decimal CalculateFinalOrderSum(long userId, decimal originalSum)
        {
            return 666;
        }
    }

class Program
    {
        static void Main(string[] args)
        {
            decimal prize = 100.1M;
            IOrderService orderService = RPCClientFactory.GetClient<IOrderService>("127.0.0.1", 9999);
            var sum1 = orderService.CalculateFinalOrderSum(500, prize);
            Console.WriteLine(sum1);

            Console.ReadLine();
        }
    }
详细代码：https://github.com/nlh774/ConAppDotNettyRPCTest

**Comment by Coldairarrow** [comment]
请升级到最新版，1.5.0已修复
