### ISSUE TITLE
这个RPC框架还有很多可以优化的地方

### ISSUE THREAD

**Issue by TimzChen** [Coldairarrow/DotNettyRPC#6]
我是做后端开发这块的，看了下这个RPC框架的源码，发现这个框架和我们公司现在使用基于WCF的RPC调用方式非常相似，从这个框架里面看到了很多可以优化的地方，不知道楼主对这方面感不感兴趣，感兴趣的话可以抽空交流下哈~

**Comment by Coldairarrow** [comment]
这个框架也仅是一个简单的框架，WCF在现在已经被弃用了

**Comment by TimzChen** [comment]
这个RPC的通讯是基于DotNetty，我们的通讯是基于WCF，但其他的实现是挺类似的，加了不少缓存在里面，减少了反射的性能损耗。

**Comment by Coldairarrow** [comment]
你说的是对的，但是这个框架我不准备深入
